### ISSUE TITLE
Wrong OnlyKey detected?

### ISSUE THREAD

**Issue by MalteFlender** [Ian2020/io.onlykey.OnlyKey-App#1] opened 2024-02-26 09:38 UTC
Hello,

currently I am trying to run the OnlyKey-App on my Fedora 39. Since the [snap app](https://github.com/trustcrypto/OnlyKey-App/issues/216#issuecomment-1963598222) failed me, I tried to build the flatpak app. The build process itself is not really that convenient (a pre build app that I can download from flathub would be way nicer), but worked out. After unlocking the OnlyKey the app actually recognizes it and wants to set it up again. But it talks about the OnlyKey DUO which is not the one I have (I have the one with the 6 buttons) and after setting new pins the app wont proceed further.

Here you can find a screenshot:
![grafik](https://github.com/Ian2020/io.onlykey.OnlyKey-App/assets/11207895/9e81c171-1ebe-4dca-a5f6-aae90fc249b8)

Can you provide a working App for Fedora 39 or enhance the CLI so it can perform all actions the app can (e.g. backup and recovery)?

**Comment by Ian2020** [comment] 2024-02-27 10:29
Hi,

I agree I would like to see the OnlyKey app on flathub too. However I think the OnlyKey organisation should be the ones to publish it rather than me. I am just a user like you and this flatpak I have built is unofficial. I see you have already added a thumbs up to the issue in their repo (https://github.com/trustcrypto/OnlyKey-App/issues/105), that's great, maybe one day they will address this and make their own flatpak.

I have the same 6 button Onlykey as you, I'll see if I can reproduce your setup problem with Fedora 39.

**Comment by JamesOsborn-SE** [comment] 2024-02-27 21:39
I have both types of keys. I had this happen once with the AUR version that's a repackaging of the deb. 
Try unplugging and restarting the app to get the right interface. 

Furthermore, I was unable to recreate this with the flatpak version.

Also, if I plug in the 6 button one after I plug in the DUO, I get the DUO interface with the slot info for the 6 button. 

I think this is all an upstream issue.

**Comment by Ian2020** [comment] 2024-11-11 14:12
I could not reproduce this, closing and hoping it's addressed upstream as per @JamesOsborn-SE comment above.

**Closed as completed by Ian2020** 2024-11-11 14:12 UTC
